name: drupal8
recipe: drupal8
config:
  webroot: docroot
  xdebug: false
  php: '7.1'
services:
  appserver:
    ssl: true
    via: apache
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
  git:
    service: appserver
