name: drupal8
recipe: drupal8
config:
  webroot: docroot
  xdebug: false
  php: '7.1'
services:
  appserver:
    ssl: true
    via: apache
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - composer
      - --ansi
  php:
    service: appserver
  mysql:
    user: root
    service: database
    description: Drop into a MySQL shell
  git:
    service: appserver
# Add in some custom event scripting
events:
  # Run some commands after `lando db-import`
  post-db-import:
    # Run `drush sqlsan` on the appserver service
    - appserver: drush sqlsan
  # Run some commands after `lando test`
  # post-test:
    # - echo "runs after test"
  # Run some commands after `lando start`
  post-start:
    - echo "Welcome back. Lando missed you!"
  post-rebuild:
    - appserver: cd $LANDO_MOUNT && composer install
